########################################################################
#       This is everything you need to modify. Change all of it!       #
########################################################################

# The name of your awesome band.
artist_name: Ami Noctu

# The name of the album, set, EP, etc.
album_name: Individual Business

# The set ID on soundcloud. See here: github.com/pearkes/singer/#retrieving_set_id
soundcloud_set_id: 7675046

# Your soundcloud application API key. See here: github.com/pearkes/singer/#retrieving_soundcloud_key
soundcloud_key: d206dbc0a13285e11bb5ca58285855d7

# Your username on SoundCloud!
soundcloud_username: pearkes

# You can sign up for a Google Anayltics account here: http://www.google.com/analytics/
# That will let you see how many people come to your site, and where they come from.
# Pretty snazzy.
google_anayltics_key:

# The link to your background image. See here: github.com/pearkes/singer/#background_image
background_image_link: http://i.imgur.com/nNfYK8B.jpg

# This intro will go on the first page.
singer_intro: |
        <p>Dark hints and sly quips, wily eyes in the candlestick glow, a fleeting masquerade of shadows cast by running feet. Absconding, piloted by moonlight. Ears perked to the whispers of the misty isles. Gather your wits, for time ticks and the raindrops drip. Don’t get caught.</p>
        <p>It’s a long way; it’s a wild way, It’s a secret, an Individual Business.</p>

# This outro will go on the first page below the track list.
singer_outro: |
        <p><a href="http://gum.co/rtTQm">Purchase</a></p>
        <p class="explain">Pay what you will. Take it for free, if need be. (just type zero in the amount box).</p>
        <p>Or, you should follow me on <a href="https://soundcloud.com/ami-noctu">SoundCloud</a>.</p>

# The font for the body. See here: github.com/pearkes/singer/#custom_fonts
body_font: Josefin Sans

# The font for headings. See here: github.com/pearkes/singer/#custom_fonts
heading_font: Dawning of a New Day

########################################################################
#        Useless Technical stuff below. Proceed with Caution!!!        #
########################################################################

markdown: redcarpet
pygments: true

